---
title: "Lab 3"
#author: "Insert Name"
date: "Math 241, Week 3"
output:
  pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
# Do not modify this chunk.
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)


```

```{r}
libs <- c('tidyverse','knitr','viridis', 'mosaic', 'Lahman', "readr", "dplyr", "tidyr", "ggplot2")
for(l in libs){
  if(!require(l,character.only = TRUE, quietly = TRUE)){
    message( sprintf('Did not have the required package << %s >> installed. Downloading now ... ',l))
    install.packages(l) 
  }
  library(l, character.only = TRUE, quietly = TRUE)
}

```

```{r}
data_science <- read_csv(file = "data/jobs_in_data.csv", show_col_types = FALSE)
dim(data_science)
```

```{r}
data_science$job_title <- as.factor(data_science$job_title)
data_science$experience_level <- as.factor(data_science$experience_level)
data_science$employment_type <- as.factor(data_science$employment_type)
data_science$work_setting <- as.factor(data_science$work_setting)
data_science$company_size <- as.factor(data_science$company_size)


model <- lm(salary ~ job_title + experience_level + employment_type + work_setting + company_size, data = data_science)

# Summarize the model
summary(model)

```

```{r}



exp_salary <- data_science %>%
  group_by(experience_level) %>%
  summarize(avg_salary = mean(salary, na.rm = TRUE))

employment_salary <- data_science %>%
  group_by(employment_type) %>%
  summarize(avg_salary = mean(salary, na.rm = TRUE))

work_salary <- data_science %>%
  group_by(work_setting) %>%
  summarize(avg_salary = mean(salary, na.rm = TRUE))

company_salary <- data_science %>%
  group_by(company_size) %>%
  summarize(avg_salary = mean(salary, na.rm = TRUE))


```

```{r}
library(cowplot)

# Plot 1: Average Salary by Experience Level
plot1 <- ggplot(data = exp_salary, aes(x = experience_level, y = avg_salary)) +
  geom_bar(stat = "identity", fill = "lightgreen") +
  theme_minimal() +
  labs(title = "Average Salary by Experience Level",
       x = "Experience Level",
       y = "Average Salary")

# Plot 2: Average Salary by Employment Type
plot2 <- ggplot(data = employment_salary, aes(x = employment_type, y = avg_salary)) +
  geom_bar(stat = "identity", fill = "lightcoral") +
  theme_minimal() +
  labs(title = "Average Salary by Employment Type",
       x = "Employment Type",
       y = "Average Salary") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot 3: Average Salary by Work Setting
plot3 <- ggplot(data = work_salary, aes(x = work_setting, y = avg_salary)) +
  geom_bar(stat = "identity", fill = "lightpink") +
  theme_minimal() +
  labs(title = "Average Salary by Work Setting",
       x = "Work Setting",
       y = "Average Salary") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plot 4: Average Salary by Company Size
plot4 <- ggplot(data = company_salary, aes(x = factor(company_size, levels = c("S", "M", "L")), y = avg_salary)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  theme_minimal() +
  labs(title = "Average Salary by Company Size",
       x = "Company Size",
       y = "Average Salary") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_discrete(labels = c("S" = "Small", "M" = "Medium", "L" = "Large"))

# Arrange the plots in a grid
combined_plot <- plot_grid(plot1, plot2, plot3, plot4, ncol = 2)

# Print the combined plot
combined_plot

```

```{r}

# gets ride of extra titles
job_title_counts <- data_science %>%
  count(job_title)

other_jobs <- job_title_counts %>%
  filter(n < 100) %>%
  pull(job_title)

data_science_grouped <- data_science %>%
  mutate(job_title_grouped = if_else(job_title %in% other_jobs, "Other", job_title))

#frequency of titles 
ggplot(data = data_science_grouped, aes(x = job_title_grouped)) +
  geom_bar(fill = "skyblue", color = "black") +
  theme_minimal() +
  labs(title = "Distribution of Job Titles (Grouped)",
       x = "Job Title",
       y = "Frequency") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```

```{r}
avg_salary_by_job <- data_science_grouped %>%
  group_by(job_title_grouped) %>%
  summarize(avg_salary = mean(salary, na.rm = TRUE))

ggplot(data = avg_salary_by_job, aes(x = job_title_grouped, y = avg_salary)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  theme_minimal() +
  labs(title = "Average Salary by Job Title",
       x = "Job Title",
       y = "Average Salary") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}

data_science$job_title <- as.factor(data_science$job_title)
data_science$experience_level <- as.factor(data_science$experience_level)
data_science$employment_type <- as.factor(data_science$employment_type)
data_science$work_setting <- as.factor(data_science$work_setting)
data_science$company_size <- as.factor(data_science$company_size)


model <- lm(salary ~  experience_level + employment_type + work_setting + company_size, data = data_science)

# Summarize the model
summary(model)


```

###### Q2:

```{r}
library(tmap)

avg_salary_by_country <- data_science %>%
  group_by(company_location) %>%
  summarize(avg_salary_in_usd = mean(salary_in_usd))

avg_salary_by_country <- avg_salary_by_country %>%
  mutate(company_location = case_when(
    company_location == "Czech Republic" ~ "Czech Rep.",
    company_location == "South Korea" ~ "Korea",
    company_location == "Central African Republic" ~ "Central African Rep.",
    company_location == "Bosnia and Herzegovina" ~ "Bosnia and Herz.",
    TRUE ~ company_location
  ))


data("World")
world_map <- merge(World, avg_salary_by_country, by.x = "name", by.y = "company_location", all.x = TRUE)

tm_shape(world_map) +
  tm_polygons(col = "avg_salary_in_usd", style = "jenks", palette = "Blues",
              main.title = "Average Salaries of Data Scientists by Country, 2020-2023",
              title = "Average Salaries by Country (USD), 2020-2023", legend.title = "Salary Range")
```

```{r}
# Plotting the breakdown of job titles by experience level
ggplot(data = data_science_grouped, aes(x = job_title_grouped, fill = experience_level)) +
  geom_bar(position = "dodge", color = "black") +
  theme_minimal() +
  labs(title = "Job Title Breakdown by Experience Level",
       x = "Job Title",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Plotting the breakdown of job titles by work setting
ggplot(data = data_science_grouped, aes(x = job_title_grouped, fill = work_setting)) +
  geom_bar(position = "dodge", color = "black") +
  theme_minimal() +
  labs(title = "Job Title Breakdown by Work Setting",
       x = "Job Title",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
ggplot(data_science_grouped)
```

###### Q3

```{r}

# Calculate the average salary for each job title and year
avg_salary_by_job_year <- data_science_grouped %>%
  group_by(job_title_grouped, work_year) %>%
  summarize(avg_salary = mean(salary, na.rm = TRUE))

# Plotting the average salary for each job title by year
ggplot(data = avg_salary_by_job_year, aes(x = job_title_grouped, y = avg_salary, fill = factor(work_year))) +
  geom_bar(stat = "identity", position = position_dodge(), color = "black") +
  theme_minimal() +
  labs(title = "Average Salary by Job Title (Factored by Year)",
       x = "Job Title",
       y = "Average Salary",
       fill = "Year") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
avg_salary_by_employtype <- data_science %>% group_by(employment_type) %>% mutate(mean = mean(salary_in_usd))
ggplot(avg_salary_by_employtype, aes(x = work_year, y = mean)) + 
  geom_point() +
  facet_wrap(~employment_type)
```
