---
title: "Project Proposal"
format: html
editor: visual
---

### Dataset Description

-   Our dataset, titled "Jobs and Salaries in Data Science," originates from \[AI Jobs\](<https://ai-jobs.net/salaries/2023/>). It encompasses various attributes crucial for understanding the landscape of data science careers

```{r, echo=FALSE}
library(tidyverse)
data_science <- read_csv(file = "data/jobs_in_data.csv", show_col_types = FALSE)
dim(data_science)
```

-   Our dataset contains 9355 observations with 12 variables.

### Reasons for Dataset Selection

-   As different career paths fall in and out of demand, it is hard to know what is a worth while pursuit in today's job market. We chose this data because we are all interested in careers in data science and we want be knowledgeable about the field as we prepare for graduation.

### Questions

**Q1. The Effect of Company-Level Demands and Characteristics on Salary**

-   Variables Involved: \`job_title\`, \`experience_level\`, \`employment_type\`, \`work_setting\`, \`company_size\`

-   Plan: We will analyze how various factors such as job title, experience level, employment type, work setting, and company size influence ones salary levels.

**Q2. Job Title Breakdown by Demographic Factors**

-   Variables Involved:\`job_title\`, \`employee_residence\`, \`age\`, \`experience_level\`, \`work_setting\`

-   Plan: See the difference in the distribution of specific job titles across different variables like location, age, experience level, and work setting.

**Q3. Evolution of Data Science Jobs and Salaries Over Time**

-   Variables Involved: \`work_year\`, \`job_title\`, \`salary\`

-   Plan: look at how the supply of data science jobs and  salaries have changed over time. Could Also be interesting to see if there's a relationship between the average salary and the number of available jobs.
